name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
      - name: Prepare project
        run: |
          cat << EOF > local.properties
          diruptio-repo.username=
          diruptio-repo.password=
          EOF
      - name: Build
        run: |
          chmod +x ./kotlin
          ./kotlin build
